//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "options")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub option_key: String,
    pub option_value: String,
    pub action_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::actions::Entity",
        from = "Column::ActionId",
        to = "super::actions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actions,
}

impl Related<super::actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Actions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
